services:
  kommit-api:
    build: .
    expose:
      - "3001"
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - ALLOWED_ORIGIN=${ALLOWED_ORIGIN}
    restart: unless-stopped
    networks:
      - nginx-proxy-manager_default

networks:
  nginx-proxy-manager_default:
    external: true
